### ISSUE TITLE
Executive Project Summary

### ISSUE THREAD

**Issue by alehechka** [alehechka/cybr-4580-pluspluspoints#7]
https://github.com/MLHale/CYBR4580-8950/blob/master/projects/undergrad-milestone1.md#executive-project-summary

## Executive Project Summary
An executive summary should be evocative. It should capture a reader and make them want to be a part of your idea. In this milestone you will write an executive summary that defines the goals and objectives of your project in language that is easily readable and mental-image evoking. I (or anyone else) should be able to read your executive summary and instantly know a) what you are doing and b) why it is important. Executive summaries should be exciting and interesting. It is the first (and likely the only) chance for you to engage your reader and, in a real world setting, would determine if your product gets funded. An executive summary does not need technical detail to describe interesting functionality. You should mention your product by name without using phrases such as "the class", "the instructor", "assignment 2" etc.

### Submission materials
You should submit a summary document (in markdown format) on your GitHub project repo. Call the file README.md and place it in the top-level directory of your GitHub project.

It should contain the following:

1. A problem statement identifying relevant issues related to your bid. The problem statement might also discuss why these issues are a problematic for society, a particular industry/sector/company/agency, or a specific technology(ies).
1. Project goals and objectives in a numbered or bulleted list that you propose to undertake to address the identified problem. Clearly identify what you are doing at a high level with minimal technical detail.
1. The merit of accomplishing the project goals and objectives in terms of how it helps end users, society, or particular industries/sectors/companies/agencies.

### Grading criteria
Your summaries will be graded as follows following:

| | Meets expectations (9-10) | Some Issues (6-8) | Does not meet expectations (0-5)|
|---|---|---|---|
|Problem statement| Clearly identifies the context of the problem addressed by your project. Answers the question - Why is this an area of interest? | Problem context not clearly identified, leaves reader wondering why the project is necessary. | Problem context unclear or not identified. |
|Project goals| Project goals are clear, concise, and in a bulleted list. Efforts are clearly tied to addressing the identified problem. Goals are stated at a high level and are free of technical jargon or unnecessary detail. | Goals are not as clear, 'in the weeds,' or not directly applicable to the problem. | No goals are identified or there are severe clarity issues. |
|Project Merit | The benefits for pursing the project are clear and tied to addressing the identified problem(s). End user, societal, and industrial benefits are stated - if relevant.| Benefits and merits of the proposed work are muddled or not tied to the problem statement. | Merits are difficult to identify or missing entirely. |
|Length| Summary is of reasonable length (no longer than 1 page, not too short)| Summary is slightly too short or too long | Summary is extremely short or long. |
|Grammar, spelling, syntax | Summary is evocative and free of grammar, spelling, or syntax issues. | Summary contains a few syntax, grammar, or spelling issues. | Summary is difficult to read due to glaring grammar, syntax, or spelling issues|
|Use of markdown| Summary should render as the project homepage on your GitHub repo. It should following markdown conventions. | Doesn't perfectly follow markdown syntax or isn't rendered on the repo home page correctly. | Doesn't use markdown or isn't displayed in the repo.|

**60 points**

### To-do
- [ ] **Problem statement:** Clearly identifies the context of the problem addressed by your project. Answers the question - Why is this an area of interest?
- [ ] **Project goals:** Project goals are clear, concise, and in a bulleted list. Efforts are clearly tied to addressing the identified problem. Goals are stated at a high level and are free of technical jargon or unnecessary detail.
- [ ] **Project Merit:** The benefits for pursing the project are clear and tied to addressing the identified problem(s). End user, societal, and industrial benefits are stated - if relevant.
- [ ] **Length:** Summary is of reasonable length (no longer than 1 page, not too short)
- [ ] **Grammar, spelling, syntax:** Summary is evocative and free of grammar, spelling, or syntax issues.
- [ ] **Use of markdown:** Summary should render as the project homepage on your GitHub repo. It should following markdown conventions.
